=== AnaNava1996/respaldo-entrega-2-tec-web/29/ejemplo10schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.w3schools.com"
xmlns="https://www.w3schools.com"
elementFormDefault="qualified">
<xs:element name="familia">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="elbebe" type="xs:string"/>
      <xs:element name="labebe" type="xs:string"/>
      <xs:element name="elbebe2" type="xs:string"/>
      <xs:element name="labebe2" type="xs:string"/>
      <xs:element name="hermano">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="apellido" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="hermana">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="apellido" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>
</xs:schema>

=== AnaNava1996/respaldo-entrega-2-tec-web/29/ejemplo10schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<familia
xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.w3schools.com ejemplo10schema.xsd">
  <elbebe>Marcel</elbebe>
  <labebe>Clara</labebe>
  <elbebe2>Adrian</elbebe2>
  <labebe2>Regina</labebe2>  
  <hermano>
    <nombre>Petronilo</nombre>
    <apellido>Perez</apellido>
  </hermano>
  <hermana>
    <nombre>Petronila</nombre>
    <apellido>Perez</apellido>
  </hermana>
</familia>
