<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
[
<!ELEMENT html (head,body)>
<!ELEMENT head (title,meta+)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT meta (#PCDATA)>
<!ELEMENT body (div)>
<!ELEMENT div (#PCDATA)>
<!ATTLIST meta charset CDATA #IMPLIED>
<!ATTLIST meta name CDATA #IMPLIED>
<!ATTLIST meta content CDATA #IMPLIED>
]>
<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body>
        <div>TODO write content</div>
    </body>
</html>