<?xml version="1.0"?>
<!DOCTYPE universidad [
<!ELEMENT universidad (profesor,alumno*,aula?,empleado+)>
<!ELEMENT profesor (#PCDATA|nombre|apellido|telefono|direccion|materias)*>                <!--Mixto-->
<!ELEMENT nombre (#PCDATA)>
<!ATTLIST nombre name CDATA #FIXED "Tamara">
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ATTLIST telefono numero (5511223344) #REQUIRED>
<!ELEMENT direccion (#PCDATA)>
<!ATTLIST direccion calle CDATA #FIXED "Highway to hell">
<!ELEMENT materias (#PCDATA)>
<!ELEMENT alumno (#PCDATA)>
<!ELEMENT aula (#PCDATA)>
<!ELEMENT empleado (#PCDATA)>
]>
<universidad>
<profesor>
<nombre name="Tamara"/>
<apellido>Morgan</apellido>
<telefono numero="5511223344"/>
<direccion calle ="Highway to hell"/>
<materias></materias>
</profesor>
<alumno>Juana</alumno>
<aula>Laboratorios</aula>
<empleado>Conserje</empleado>
</universidad>