=== AnaNava1996/respaldo-entrega-2-tec-web/25/ejemploschema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.w3schools.com"
xmlns="https://www.w3schools.com"
elementFormDefault="qualified">
<xs:element name="persona">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="nombre" type="xs:string"/>
      <xs:element name="apellido" type="xs:string"/>
      <xs:element name="estatura" type="xs:decimal"/>
      <xs:element name="edad" type="xs:integer"/>
      <xs:element name="vivo_o_muerto" type="xs:boolean"/>
      <xs:element name="fecha_de_nacimiento" type="xs:date"/>
      <xs:element name="hora" type="xs:time"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
</xs:schema>

=== AnaNava1996/respaldo-entrega-2-tec-web/25/ejemploschema.xml
<?xml version="1.0" encoding="UTF-8"?>
<persona
xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.w3schools.com ejemploschema.xsd">
  <nombre>Maria</nombre>
  <apellido>La del Barrio</apellido>
  <estatura>1.6</estatura>
  <edad>60</edad>
  <vivo_o_muerto>1</vivo_o_muerto>
  <fecha_de_nacimiento>1960-05-13</fecha_de_nacimiento>
  <hora>07:00:00</hora>
</persona>
